model: lgbm

targets:
  - ret_1d_f
  - ret_5d_f
  - ret_21d_f

features:
  - log_return
  - volume_z
  - price_norm

params:
  n_estimators: 100
  learning_rate: 0.05
  max_depth: 6
  subsample: 0.8
  colsample_bytree: 0.8
