#!/usr/bin/env python3
"""
create_research_db.py
=====================
Creates a frozen research snapshot of the production database for safe
ML experimentation.

This script runs ONCE from the project root. After it completes the research
DB is frozen and never updated. All ML research notebooks connect to the
research DB, never the production DB.

What it copies:
    feat_targets        — training targets (2015-2025)
    feat_fundamental    — fundamental features (2015-2025)
    feat_vol_sizing     — volatility features (2015-2025)
    feat_beta           — beta features (2015-2025)
    feat_price_action   — price action features (2015-2025)
    feat_momentum_v2    — momentum features (2015-2025, universe tickers only)
    sep_base_academic   — daily prices for universe (2015-2025)
    tickers             — metadata (all rows, no date filter)

What it does NOT copy:
    sep, sf1, sf2, sf3  — raw Sharadar tables (not needed for ML)
    feat_matrix_v2      — output table, regenerated by pipeline
    feat_composite_*    — not used in ML training
    feat_alpha_ml_*     — model outputs, regenerated by training scripts

Key filters applied:
    - Date range: 2015-01-01 to 2025-12-31
    - feat_momentum_v2: filtered to universe tickers in feat_targets only
      (full table has 19,643 tickers vs 2,335 in active universe)
    - tickers duplicates: both SF1 and SEP rows are copied as-is
      (training scripts handle dedup with DISTINCT ticker, sector)

Usage:
    python scripts/research/create_research_db.py \
        --source data/kairos.duckdb \
        --dest data/kairos_research.duckdb

    The dest path should be on the same SSD as the source for speed.
    Estimated size: <10GB. Estimated time: 5-15 minutes.

Safety:
    - Source DB is opened read-only. It is never modified.
    - If dest DB already exists the script will refuse to overwrite
      unless --overwrite flag is passed.
    - Row counts are verified after each table copy.
"""

import argparse
import logging
import sys
import time
from pathlib import Path

import duckdb

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s: %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S"
)
logger = logging.getLogger(__name__)

# =============================================================================
# DATE RANGE
# =============================================================================

START_DATE = '2015-01-01'
END_DATE   = '2025-12-31'

# =============================================================================
# TABLE DEFINITIONS
# =============================================================================
# Each entry is:
#   (table_name, has_date_filter, extra_filter)
# has_date_filter: True  = apply START_DATE/END_DATE filter on date column
#                  False = copy all rows (tickers has no date column)
# extra_filter: additional WHERE clause fragment or None

TABLES = [
    {
        'name':            'feat_targets',
        'has_date_filter': True,
        'extra_filter':    None,
        'description':     'Training targets (ret_5d_f, label_5d_up)',
    },
    {
        'name':            'feat_fundamental',
        'has_date_filter': True,
        'extra_filter':    None,
        'description':     'Forward-filled SF1 fundamentals',
    },
    {
        'name':            'feat_vol_sizing',
        'has_date_filter': True,
        'extra_filter':    None,
        'description':     'Volatility features (vol_21, vol_63, vol_blend)',
    },
    {
        'name':            'feat_beta',
        'has_date_filter': True,
        'extra_filter':    None,
        'description':     'Beta features (beta_21d, beta_63d, beta_252d, resid_vol_63d)',
    },
    {
        'name':            'feat_price_action',
        'has_date_filter': True,
        'extra_filter':    None,
        'description':     'Price action features (hl_ratio, range_pct, ret_21d, ret_5d)',
    },
    {
        'name':            'feat_momentum_v2',
        'has_date_filter': True,
        'extra_filter':    (
            "AND ticker IN ("
            "    SELECT DISTINCT ticker FROM feat_targets"
            ")"
        ),
        'description':     'Momentum features — filtered to universe tickers only',
    },
    {
        'name':            'sep_base_academic',
        'has_date_filter': True,
        'extra_filter':    None,
        'description':     'Daily prices for academic universe',
    },
    {
        'name':            'tickers',
        'has_date_filter': False,
        'extra_filter':    None,
        'description':     'Ticker metadata (sector, exchange, category)',
    },
]


# =============================================================================
# HELPERS
# =============================================================================

def build_select_query(source_db_path: str, table: dict) -> str:
    """
    Build the SELECT query for copying one table from the source DB.
    Uses an ATTACH approach so both DBs are open simultaneously.
    """
    name         = table['name']
    date_filter  = table['has_date_filter']
    extra_filter = table['extra_filter']

    if date_filter:
        where = (
            f"WHERE CAST(date AS DATE) >= '{START_DATE}' "
            f"  AND CAST(date AS DATE) <= '{END_DATE}'"
        )
        if extra_filter:
            where += f"\n  {extra_filter}"
    else:
        if extra_filter:
            where = f"WHERE {extra_filter}"
        else:
            where = ""

    return f"SELECT * FROM source.{name} {where}"


def verify_row_count(dest_con, table_name: str, expected: int):
    """Verify row count in dest matches expected."""
    actual = dest_con.execute(
        f"SELECT COUNT(*) FROM {table_name}"
    ).fetchone()[0]

    if actual != expected:
        raise ValueError(
            f"Row count mismatch for {table_name}: "
            f"expected {expected:,}, got {actual:,}"
        )
    return actual


# =============================================================================
# MAIN COPY LOGIC
# =============================================================================

def create_research_db(source_path: str, dest_path: str):
    """
    Copy filtered tables from source DB to dest DB.
    Source is opened read-only. Dest is created fresh.
    """

    logger.info("=" * 70)
    logger.info("CREATING RESEARCH DATABASE")
    logger.info("=" * 70)
    logger.info(f"Source: {source_path}")
    logger.info(f"Dest:   {dest_path}")
    logger.info(f"Dates:  {START_DATE} to {END_DATE}")
    logger.info("")

    # Open dest DB (writable, freshly created)
    dest_con = duckdb.connect(dest_path)

    # Attach source DB as read-only
    dest_con.execute(f"""
        ATTACH '{source_path}' AS source (READ_ONLY)
    """)

    total_start = time.time()
    summary = []

    for table in TABLES:
        name        = table['name']
        description = table['description']

        logger.info(f"Copying {name}...")
        logger.info(f"  {description}")

        t_start = time.time()

        # Build SELECT from source
        select_sql = build_select_query(source_path, table)

        # Count source rows first so we can verify after copy
        count_sql = f"SELECT COUNT(*) FROM ({select_sql})"
        source_count = dest_con.execute(count_sql).fetchone()[0]
        logger.info(f"  Source rows: {source_count:,}")

        # Drop if exists in dest (safety — should not happen on fresh DB)
        dest_con.execute(f"DROP TABLE IF EXISTS {name}")

        # Create table in dest from source query
        dest_con.execute(f"""
            CREATE TABLE {name} AS {select_sql}
        """)

        # Verify
        dest_count = verify_row_count(dest_con, name, source_count)

        elapsed = time.time() - t_start
        logger.info(f"  Copied {dest_count:,} rows in {elapsed:.1f}s ✓")

        summary.append({
            'table':   name,
            'rows':    dest_count,
            'seconds': elapsed,
        })

    # Detach source
    dest_con.execute("DETACH source")

    total_elapsed = time.time() - total_start

    # ==========================================================================
    # SUMMARY
    # ==========================================================================

    logger.info("")
    logger.info("=" * 70)
    logger.info("RESEARCH DB CREATION COMPLETE")
    logger.info("=" * 70)
    logger.info(f"  {'Table':<25} {'Rows':>12} {'Seconds':>10}")
    logger.info(f"  {'-'*50}")

    total_rows = 0
    for s in summary:
        logger.info(
            f"  {s['table']:<25} {s['rows']:>12,} {s['seconds']:>10.1f}s"
        )
        total_rows += s['rows']

    logger.info(f"  {'-'*50}")
    logger.info(f"  {'TOTAL':<25} {total_rows:>12,} {total_elapsed:>10.1f}s")
    logger.info("")
    logger.info(f"Research DB location: {dest_path}")
    logger.info("")
    logger.info("This database is now frozen. Do not run this script again")
    logger.info("unless you want to rebuild from scratch with --overwrite.")
    logger.info("")
    logger.info("Next step: connect notebooks to research DB at:")
    logger.info(f"  con = duckdb.connect('{dest_path}', read_only=True)")

    dest_con.close()


# =============================================================================
# VALIDATION QUERY
# =============================================================================

def validate_research_db(dest_path: str):
    """
    Run a quick sanity check on the research DB after creation.
    Verifies joins work correctly and key columns are present.
    """

    logger.info("")
    logger.info("=" * 70)
    logger.info("VALIDATING RESEARCH DB")
    logger.info("=" * 70)

    con = duckdb.connect(dest_path, read_only=True)

    # Check all tables exist
    tables_in_db = con.execute("SHOW TABLES").fetchdf()['name'].tolist()
    expected = [t['name'] for t in TABLES]

    for t in expected:
        status = "✓" if t in tables_in_db else "✗ MISSING"
        logger.info(f"  {t:<25} {status}")

    # Verify tickers join works cleanly (the DISTINCT fix)
    dupes = con.execute("""
        SELECT COUNT(*) FROM (
            SELECT ticker, COUNT(*) as cnt
            FROM (SELECT DISTINCT ticker, sector FROM tickers WHERE sector IS NOT NULL)
            GROUP BY ticker
            HAVING COUNT(*) > 1
        )
    """).fetchone()[0]

    if dupes == 0:
        logger.info("\n  Tickers DISTINCT join: ✓ no duplicates after dedup")
    else:
        logger.warning(f"\n  Tickers DISTINCT join: ✗ {dupes} tickers still have multiple sectors")

    # Verify feat_momentum_v2 is filtered to universe
    momentum_tickers = con.execute(
        "SELECT COUNT(DISTINCT ticker) FROM feat_momentum_v2"
    ).fetchone()[0]
    universe_tickers = con.execute(
        "SELECT COUNT(DISTINCT ticker) FROM feat_targets"
    ).fetchone()[0]

    logger.info(f"\n  feat_momentum_v2 tickers: {momentum_tickers:,}")
    logger.info(f"  feat_targets tickers:     {universe_tickers:,}")

    if momentum_tickers <= universe_tickers:
        logger.info("  Universe filter: ✓ momentum tickers within universe")
    else:
        logger.warning("  Universe filter: ✗ momentum has more tickers than universe")

    # Verify date ranges
    logger.info("\n  Date ranges:")
    for t in [t for t in TABLES if t['has_date_filter']]:
        name = t['name']
        result = con.execute(f"""
            SELECT MIN(date) as min_d, MAX(date) as max_d
            FROM {name}
        """).fetchone()
        logger.info(f"  {name:<25} {str(result[0])[:10]} to {str(result[1])[:10]}")

    # Verify a simple training join works
    logger.info("\n  Test join (feat_targets + feat_fundamental + tickers):")
    test = con.execute("""
        SELECT COUNT(*) as rows
        FROM feat_targets t
        JOIN feat_fundamental f ON t.ticker = f.ticker AND t.date = f.date
        JOIN (SELECT DISTINCT ticker, sector FROM tickers WHERE sector IS NOT NULL) tk
            ON t.ticker = tk.ticker
        WHERE t.ret_5d_f IS NOT NULL
    """).fetchone()[0]
    logger.info(f"  Joined rows: {test:,} ✓")

    con.close()
    logger.info("")
    logger.info("Validation complete. Research DB is ready for use.")


# =============================================================================
# MAIN
# =============================================================================

def main():
    parser = argparse.ArgumentParser(
        description="Create frozen research DB from production DB"
    )
    parser.add_argument(
        "--source",
        required=True,
        help="Path to production DuckDB (read-only)"
    )
    parser.add_argument(
        "--dest",
        required=True,
        help="Path for new research DuckDB (will be created)"
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite dest DB if it already exists"
    )
    parser.add_argument(
        "--skip-validation",
        action="store_true",
        help="Skip post-creation validation"
    )
    args = parser.parse_args()

    dest_path = Path(args.dest)

    # Safety check — do not silently overwrite
    if dest_path.exists():
        if args.overwrite:
            logger.warning(f"Overwriting existing research DB: {dest_path}")
            dest_path.unlink()
        else:
            logger.error(
                f"Research DB already exists: {dest_path}\n"
                f"Pass --overwrite to replace it, or choose a different path."
            )
            sys.exit(1)

    # Create parent directory if needed
    dest_path.parent.mkdir(parents=True, exist_ok=True)

    # Create the research DB
    create_research_db(args.source, args.dest)

    # Validate
    if not args.skip_validation:
        validate_research_db(args.dest)


if __name__ == "__main__":
    main()